### ISSUE TITLE
 TypeError: Lsm303Driver is not a constructor

### ISSUE THREAD

**Issue by anking** [101100/lsm303-rx#5]
When trying to run a sample this error comes up:
```
lsm303 = new Lsm303Driver(options);
         ^

TypeError: Lsm303Driver is not a constructor
    at Object.<anonymous> (/home/pi/gps/accel.js:10:10)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
```

**Comment by 101100** [comment]
Sorry, the README has the wrong `require` line.  I'll update it shortly, but in the mean time, change the requires line to:

```js
var Lsm303Driver = require("lsm303-rx").Lsm303Driver;
```

**Comment by 101100** [comment]
v2.0.1 has the correct README.
